apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: mysqldump
  namespace: golden-key
spec:
  schedule:  "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: registry.gitlab.com/serapion/timvalores/gk-web/mysql-backup
            env:
              - name: ALL_DATABASES
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: all_databases
              - name: DB_HOST_CRM
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: dbhostcrm
                    - name: DB_HOST_USER
                    valueFrom:
                      configMapKeyRef:
                        name: mysqldump
                        key: dbhostuser
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbuser
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbpass
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /mysqldump
                name: mysqldump
          volumes:
            - name: mysqldump
              hostPath:
                path: /home/core/mysqldump
          restartPolicy: OnFailure
